// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RockGym.Database;

#nullable disable

namespace RockGym.Migrations
{
    [DbContext(typeof(RockDbContext))]
    partial class RockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RockGym.Models.GroupTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrainerSurname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrainerYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GroupTrainings");
                });

            modelBuilder.Entity("RockGym.Models.GroupTrainingFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GroupTrainingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GroupTrainingFeedbacks");
                });

            modelBuilder.Entity("RockGym.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("SubscriptionEnds")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SubscriptionStarts")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
